# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 916bbe6bed3415b43974a8591534dc54061b62cd683040c15c8f7fd9024d1c311c549960667397cfeddaa51458c0a60278a43b8beb29fe157358dbfc96f2fcec

test:
  secret_key_base: de37a2e9e30ccc9f97a43901b744a90e346b821baf070f6fd563abd47c19f6f5129d896abd1ecd88578e238ecfe17c19a66603a081b1f8d9b8367bb7f3e537c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
